### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Amby713** [lakafior/RVBuilderHelper#1]
$ wget https://raw.githubusercontent.com/lakafior/RVBuilderHelper/main/rvgui.sh

chmod a+x rvgui.sh

./rvgui.sh
--2022-08-09 10:03:25--  https://raw.githubusercontent.com/lakafior/RVBuilderHelper/main/rvgui.sh
Resolving raw.githubusercontent.com... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1636 (1.6K) [text/plain]
Saving to: ‘rvgui.sh.1’

rvgui.sh.1                 100%[=======================================>]   1.60K  --.-KB/s    in 0s

2022-08-09 10:03:26 (40.8 MB/s) - ‘rvgui.sh.1’ saved [1636/1636]

./rvgui.sh: line 8: syntax error near unexpected token `newline'
./rvgui.sh: line 8: `<!DOCTYPE html>'
~ $

**Comment by Amby713** [comment]
Wrong file on my end, sorry

**Comment by lakafior** [comment]
Yeah,when you download script again it is not overwritten so it was saved as ‘rvgui.sh.1’
If you want to redownload with the same name, you can use:
wget -O rvgui.sh https://raw.githubusercontent.com/lakafior/RVBuilderHelper/main/rvgui.sh
